# Generated by Django 2.2.5 on 2020-11-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201125_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilites',
        ),
    ]
